name: Workflow sequentiel

on: 
  push:
    tags:
      - release*

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VAR1: '2'
    steps:
    - name: Affichage VAR1
      run: echo $VAR1
  
  job2:
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Job1 raté
      run: echo 'Le job1 a échoué !'
  
  job3:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Partie bonus
      run: echo "Il s'execute peu importe le résultat !"

    